package autofacets.base;

/**
 * @author niravpatel
 */

public interface WebLocators {

    public interface Homepage {
        public String registerascarcompany_link_nl = "//a[contains(text(),'Adverteren')]";
        public String registerUser_link_nl = "//a[contains(text(),'Registreren')]";
        public String loginUser_link_nl = "//a[contains(text(),'Inloggen')]";
        public String forgotpassword_link_nl = "//a[contains(text(),'Wachtwoord vergeten?')]";
        public String contact_link_nl = "//a[contains(@href,'https://test.eurostocks.nl/nl/contact-us')]";
        public String contactDealer_link_nl = "//div[@class='row mb50 xsmb20']//div[2]//a[1]";
        public String parts_menu_nl = "//h2[contains(text(),'ONDERDELEN')]";
        public String searchDealer_input = "//input[@id='search']";
        public String vehicles_menu_nl = "//h2[contains(text(),'VOERTUIGEN')]";
        public String wheel_menu_nl = "//h2[contains(text(),'WIELEN & BANDEN')]";
        public String search_fld = "//input[@id='MainSearch' or @id='search']";
        public String search_result = "//h1[contains(text(),'Resultaten voor')]";
        public String searchDealer_result = "//h2[contains(text(),'Resultaten voor') or contains(text(),'Results for')]";
        public String search_result_found = "//p[contains(text(),'Resultaten')]";
        public String searchResultDealer_found = "//span[contains(text(),'producten')]";
        public String search_result_notfound = "//div[contains(text(),'Geen resultaten gevonden')]";
        public String dropdownMain_btn = "//*[@name='MainCategoryId']";
        public String searchMain_btn = "//*[@class='btn search-btn searchButton']";
        public String autoSearch_drpdown = "//*[@class='autosearch-results']";
        public String autoSearch_options = "//div[contains(text(),\"Auto's\") or contains(text(),'Spie')]";
        public String pagination_options = "//*[@class='pagination']";
        public String sorting_options = "//select[@id='sorting']";
        public String firstSection_option = "//*[@class='col-lg-4 col-md-6 col-sm-6']//following-sibling::div[@class='content']";
        public String firstSectionDealer_option = "//*[@class='col-lg-4 col-md-6 col-sm-6 ng-star-inserted']";
        // Dealer Website
        public String navigation_menu = "//div[@id='open']";
        public String user_icon = "//div[@class='flmid width100 flspacebetween']//div//i[@class='far fa-user']";
        public String close_icon = "//div[@id='close']";
        public String register_option = "//a[@id='mobi2']";
        public String login_option = "//a[@id='mobi1']";
    }

    public interface ContactPage {
        public String contactpage_lbl_nl = "//h1[contains(text(),'Neem contact op')]";
        public String addressTitle_lbl_nl = "//h6[contains(text(),'EuroStocks B.V.')]";
        public String addressTitleDealer_lbl_nl = "//h6[normalize-space()='Otosan Automotive BV']";
        public String address_lbl_nl = "//p[contains(text(),'Jacob van Lennepkade 255 hs') or contains(text(),'1054 ZS Amsterdam') or contains(text(),' Nederland')]";
        public String addressDealer_lbl_nl = "//p[contains(text(),'Arizonadreef 4 1') or contains(text(),'3565 AP Utrecht') or contains(text(),' Nederland')]";
        public String contactus_btn_nl = "//button[contains(text(),'Versturen')]";
        public String name_msg_nl = "//span[contains(text(),'Naam is vereist')]";
        public String email_msg_nl = "//span[contains(text(),'Email adres is vereist')]";
        public String question_msg_nl = "//span[contains(text(),'Vraag/opmerking is vereist')]";
        public String contact_btn_nl = "//span[contains(text(),'Bericht') or contains(text(),'Message')]";
        public String contactApp_btn_nl = "//span[contains(text(),'App')]";
        public String contactCall_btn_nl = "//span[contains(text(),'Bel') or contains(text(),'Call')]";
        public String addProduct_btn_nl = "//a[@id='add-product-in-slider']";
        public String name_input = "//input[@placeholder='Naam *']";
        public String email_input = "//input[@placeholder='Email *']";
        public String phoneNumber_input = "//input[@placeholder='Telefoonnummer' or @placeholder='Telefoonnummer *']";
        public String message_input = "//textarea[@id='addContactUsDetails.Question']";
        public String contactEmail_lbl = "//a[contains(text(),'Bedankt voor uw contactaanvraag')]";
        public String successAlert_lbl = "//div[contains(text(),'Bedankt voor uw bericht, we zullen spoedig contact') or contains(text(),'Thank you for your message, we will contact you soon!')]";
        public String deleteEmail_btn = "//button[@id='trash_but']//*[local-name()='svg']";
    }

    public interface UserRegistrationPage {
        // Registration Field
        public String registerasUser_btn_nl = "//button[contains(text(),'Registreren')]";
        public String firstname_msg_nl = "//span[contains(text(),'Voornaam is vereist')]";
        // error message on last name
        public String lastname_msg_nl = "//span[contains(text(),'Achternaam is vereist') or contains(text(),'Last Name is required')]";
        public String postalcode_msg_nl = "//span[contains(text(),'Postcode is vereist')]";
        public String housernumber_msg_nl = "//span[contains(text(),'Huisnummer is vereist')]";
        public String street_msg_nl = "//span[contains(text(),'Straat is vereist')]";
        public String city_msg_nl = "//span[contains(text(),'Stad is vereist')]";
        public String pnumber_msg_nl = "//span[contains(text(),'Telefoonnummer is vereist')]";
        public String email_msg_nl = "//span[contains(text(),'Email adres is vereist')]";
        public String confirmemail_msg_nl = "//span[contains(text(),'Email nogmaals opgeven is vereist')]";
        public String password_msg_nl = "//span[contains(text(),'Wachtwoord is vereist')]";
        public String confirmpassword_msg_nl = "//span[contains(text(),'Wachtwoord nogmaals opgeven is vereist')]";
        public String captch_msg_nl = "//span[contains(text(),'Captcha is vereist')]";
        // Login Field
        public String loginUser_btn_nl = "//button[contains(text(),'Inloggen') or contains(text(),'Login')]";
        public String loginemail_msg_nl = "//span[contains(text(),'E-mail is vereist')]";
        public String loginpassword_msg_nl = "//span[contains(text(),'Wachtwoord vereist')]";
        public String email_input_nl = "//input[@id='txtusername']";
        public String password_input_nl = "//input[@name='loginObj.Password']";
        // Forgot Password Field
        public String forgot_btn_nl = "//button[contains(text(),'Versturen')]";
        public String loginemailforgot_msg_nl = "//span[contains(text(),'E-mailadres is benodigd')]";
    }

    public interface RegisterAsCarCompany {
        public String verify_lbl_nl = "//h1[contains(text(),'INFORMATIE AANVRAGEN')]";
        public String adverteren_lbl_nl = "//td[contains(text(),'Adverteren met EuroStocks')]";
        public String companyname_txt = "//*[@name='addCarRegiStration.CompanyName']";
        public String companyWebsite_txt = "//input[@name='addCarRegiStration.Website']";
        public String regphonenumber_txt = "//*[@name='addCarRegiStration.Phonenumber']";
        public String emailCarCompany_txt = "//*[@name='addCarRegiStration.Email']";
        public String submit_btn_nl = "//button[contains(text(),'Verzend')]";
        public String companyname_msg_nl = "//span[contains(text(),'Bedrijfsnaam is vereist')]";
        public String firstnamereg_msg_nl = "//span[contains(text(),'Voornaam is vereist')]";
        public String lastnamereg_msg_nl = "//span[contains(text(),'Achternaam is vereist')]";
        public String pnumberreg_msg_nl = "//span[contains(text(),'Telefoonnummer is vereist')]";
        public String emailreg_msg_nl = "//span[contains(text(),'Email is vereist')]";
        public String contact_btn = "//button[normalize-space()='Verzend']";
        public String successAlert_msg = "//div[contains(text(),'Informatie succesvol aangevraagd. We nemen binnenk')]";
        public String contactEmailReg_lbl = "//a[contains(text(),'EuroStocks N Automation, leuk dat je interes')]";
        public String deleteEmailReg_btn = "//button[@id='trash_but']//*[local-name()='svg']";
    }


    public interface AddProducts {
        public String dropdown_btn = "//*[@name='MainCategoryId']";
        public String search_btn = "//*[@class='btn search-btn searchButton']";
        public String buy_btn = "//*[@class='btn btn-primary ProductAddedInCart ng-star-inserted' or @class='btn btn-primary ProductAddedInCart']";
        public String order_btn = "//a[contains(text(),'Ik ga bestellen') or contains(text(),'Continue to checkout')]";
        public String orderDealer_btn = "//a[contains(text(),'Door naar afrekenen') or contains(text(),'Continue to checkout')]";
        public String shoppingPage_lbl = "//h2[contains(text(),'Winkelmand')]";
        public String shoppingPageDealer_lbl = "//h1[contains(text(),'Winkelwagen')]";
        public String checkout_btn = "//a[contains(text(),'Door naar afrekenen')]";
        public String totalAmount_lbl = "//*[contains(text(),'Totaalbedrag')]";
        public String data_lbl = "//h1[contains(text(),'Jouw gegevens') or contains(text(),'Uw gegevens')]";
        public String firstname_txt = "//*[@placeholder='Voornaam *']";
        public String middlename_txt = "//*[@placeholder='Tussenvoegsel' or @placeholder='Toevoeging' or @placeholder='Midden-naam']";
        public String lastname_txt = "//*[@placeholder='Achternaam *']";
        public String address_txt = "//*[@name='CheckOutObj.userData.checkoutAddresses.InvoiceCountry']";
        public String address_input = "//select[@name='addRegiStration.Address.Country']";
        public String postalcode_txt = "//*[@placeholder='Postcode *']";
        public String housenumber_txt = "//*[@placeholder='Huisnummer *']";
        public String houseext_txt = "//*[@placeholder='Verlenging']";
        public String houseextDealer_txt = "//input[@name='CheckOutObj.userData.checkoutAddresses.InvoiceHouseNumberExtension']";
        public String houseext_input = "//input[@id='houseextension']";
        public String street_txt = "//*[@placeholder='Straat *']";
        public String city_txt = "//*[@placeholder='Stad*' or @placeholder='Stad *' or @placeholder='Plaats *']";
        public String email_txt = "//*[@type='e-mail']";
        public String phonenumber_txt = "//*[@name='CheckOutObj.userData.phoneNumber' or @id='phonenumber']";
        public String licenceplate_txt = "//*[@name='CheckOutObj.userData.licensePlate' or @id='licenseplate']";
        public String email_input = "//input[@name='addRegiStration.Email']";
        public String confirmEmail_input = "//input[@name='addRegiStration.confirmEmail']";
        public String password_input = "//input[@name='addRegiStration.Password']";
        public String confrimPassword_input = "//input[@name='addRegiStration.confirmPassword']";
        public String idel_btn = "//input[@id='ideal']";
        public String further_btn = "//button[contains(text(),'Verder')]";
        public String overview_lbl = "//h1[contains(text(),'Overzicht')]";
        public String finalorder_btn = "//*[@class='btnCheckOut btn btn-primary autowidth CheckoutFuture']";
        public String contactEmail_lbl = "//a[contains(text(),'Registratie voltooien bij')]";
        public String successAlert_lbl = "//div[contains(text(),'Account succesvol aangevraagd') or contains(text(),'Account applied for successfully')]";
        public String deleteEmail_btn = "//button[@id='trash_but']//*[local-name()='svg']";
        public String register_btn = "//button[normalize-space()='Registreren']";
        // all status method buttons
        public String open_btn = "//span[contains(text(),'Open')]";
        public String paid_btn = "//span[contains(text(),'Paid')]";
        public String failed_btn = "//span[contains(text(),'Failed')]";
        public String canceled_btn = "//span[contains(text(),'Canceled')]";
        public String expired_btn = "//span[contains(text(),'Expired')]";
        public String continue_btn = "//button[contains(text(),'Continue')]";
        // Open order
        public String openorderVerification_lbl = "//p[contains(text(),\"Momenteel staat de betaalstatus nog op 'open'.\")]";
        // Paid order
        public String confirmorder_lbl = "//h1[contains(text(),'Bedankt voor je bestelling')]";
        public String confirmorderVerification_lbl = "//p[contains(text(),'Een orderbevestiging is gemaild naar')]";
        // Failed order
        public String failedorder_lbl = "//h1[contains(text(),'Er is iets mis gegaan tijdens de betaling.')]";
        public String failedorderVerification_lbl = "//p[contains(text(),'Mocht je alsnog je bestelling willen voltooien sta')]";
        // Canceled order
        public String caneclorder_lbl = "//h1[contains(text(),'De betaling is geannuleerd.')]";
        public String cancelorderVerification_lbl = "//p[contains(text(),'Mocht je alsnog je bestelling willen voltooien sta')]";
        // Expired order
        public String expiredorderFinal_lbl = "//h1[contains(text(),'De betaling is verlopen.')]";
        public String expiredorder_lbl = "//p[contains(text(),'The payment has been set to expired successfully. ')]";
        public String expiredorderVerificationFinal_lbl = "//p[contains(text(),'Mocht je alsnog je bestelling willen voltooien sta')]";
        public String expiredorderVerification_lbl = "//code[contains(text(),'expired')]";
        public String conshopping_btn = "//a[contains(text(),'Ga door met winkelen') or contains(text(),'Doorgaan met winkelen')]";
        public String mainSearch_fld = "//input[@id='MainSearch' or @id='search']";
        //*[@placeholder='Username' and @name='email']
    }

    public interface LoginPageBackEnd {
        public String email_fld = "//*[@placeholder='Gebruikersnaam' and @name='email']";
        public String password_fld = "//input[@id='password-field']";
        public String signin_btn = "//button[contains(text(),' aanmelden')]";
        public String user_lbl = "//*[@class='proxima-nova-light-regular afterLoginHeaderText']";
        public String business_opt = "//span[contains(text(),'Bedrijven')]";
        public String locations_opt = "//span[contains(text(),'Locatie')]";
        public String websites_opt = "//span[contains(text(),'Websites')]";
        public String bestellingen_opt = "//span[contains(text(),'Bestellingen')]";
        public String aanvragen_opt = "//span[contains(text(),'Aanvragen')]";
        public String lead_management_opt = "//span[contains(text(),'Lead Management')]";
        public String producten_opt = "//span[contains(text(),'Producten')]";
        public String mobile_opt = "(//span[contains(text(),'Mobile.de')])[1]";
        public String assortiment_opt = "(//span[contains(text(),'Assortiment')])[1]";
        public String tools_opt = "(//span[contains(text(),'Tools')])[1]";
        public String bulkWijzigen_opt = "//span[contains(text(),'Bulk wijzigen')]";
        public String adsOverzicht_opt = "//span[contains(text(),'Ads overzicht')]";
        public String categorieën_opt = "//span[contains(text(),'Categorieën')]";
        public String kenmerken_opt = "//span[contains(text(),'Kenmerken')]";
        public String eigenschappen_opt = "//span[contains(text(),'Eigenschappen')]";
        public String mobileDeAccounts_opt = "//span[contains(text(),'Mobile.de accounts')]";
        public String mobileDeAccountsDetails_opt = "//span[contains(text(),'mobile.de verzoek details')]";
        public String mobileDeAccountsMapping_opt = "//span[contains(text(),'mobile.de mapping')]";
        public String administratie_opt = "(//span[contains(text(),'Administratie')])[1]";
        public String emailTemplates_opt = "//span[contains(text(),'Email templates')]";
        public String emailTemplates_search_fld = "//*[@placeholder='Zoek op Onderwerp']";
        public String klanten_opt = "//span[contains(text(),'Klanten')]";
        public String klanten_search_fld = "//*[@placeholder='Zoek op Email, Naam van persoon, Land , Stad']";
        public String betaalmethodes_opt = "//span[contains(text(),'Betaalmethodes')]";
        public String betaalmethodes_search_fld = "//*[@placeholder='Zoek op Naam, Betaalprovider']";
        public String prijsregels_opt = "//span[contains(text(),'Prijsregels')]";
        public String prijsregels_search_fld = "//*[@placeholder='Zoek op Naam']";
        public String marktplaatsTarieven_opt = "//span[contains(text(),'Marktplaats tarieven')]";
        public String marktplaatsTarieven_search_fld = "//*[@placeholder='  MP hoofdcategorie, MP subcategorie, Prijsregel']";
        public String dehandsPrijsregels_opt = "//span[contains(text(),'2dehands prijsregels')]";
        public String dehandsPrijsregels_search_fld = "//*[@placeholder='  2dehands hoofdcategorie , 2dehands subcategorie, Prijsregels']";
        public String systeemgebruikers_opt = "//span[contains(text(),'Systeemgebruikers')]";
        public String systeemgebruikers_search_fld = "//*[@placeholder='Zoek op Voornaam, Achternaam, Email']";
        public String verzendstaffels_opt = "//span[contains(text(),'Verzendstaffels')]";
        public String verzendstaffels_search_fld = "//*[@placeholder='Zoek op Van, Tot, Verzendkosten']";
        public String CMSGroepen_opt = "//span[contains(text(),'CMS Groepen')]";
        public String CMSGroepen_search_fld = "//*[@placeholder='Zoek op Groepnaam, Weergave tekst']";
        public String CMSPagina_opt = "//span[contains(text(),\"CMS Pagina's\")]";
        public String CMSPagina_search_fld = "//*[@placeholder='Zoek op Paginanaam']";
        public String APIPartners_opt = "//span[contains(text(),'API Partners')]";
        public String APIPartners_search_fld = "//*[@placeholder='Zoek op Voornaam, Achternaam, Email']";
        public String prijsregelss_opt = "(//span[contains(text(),'Prijsregels')])[2]";
        public String prijsregelss_search_fld = "//*[@placeholder='Zoek op Pakketnaam']";
        public String keywordsVertalingen_opt = "//span[contains(text(),'Keywords vertalingen')]";
        public String keywordsVertalingen_search_fld = "//*[@placeholder='Zoek op Trefwoord']";
        public String zoekTrefwoorden_opt = "//span[contains(text(),'Zoekwoorden')]";
        public String zoekTrefwoorden_search_fld = "//*[@placeholder='Zoek op Trefwoord']";
        public String merken_opt = "//span[contains(text(),'Merken')]";
        public String merken_search_fld = "//*[@placeholder='Zoek op Merk naam']";
        public String modellen_opt = "//span[contains(text(),'Modellen')]";
        public String modellen_search_fld = "//*[@placeholder='Zoek op Model naam']";
        public String modelgroepen_opt = "//span[contains(text(),'Modelgroepen')]";
        public String modelgroepen_search_fld = "//*[@placeholder='Zoek op Model groep']";
        public String voertuigregels_opt = "//span[contains(text(),'Voertuigregels')]";
        public String BPMFuelType_opt = "//span[normalize-space()='BPM FuelType']";
        public String voertuigregels_search_fld = "//*[@placeholder='Zoek op Make, Model, Vehicle Type, Category']";
        public String Voertuigen_opt = "//span[contains(text(),'Voertuigen')]";
        public String table_data = "//*[contains(text(),'Geen resultaten') or contains(text(),'Aantal resultaten')]";
        public String inactive_radioBtn = "//label[normalize-space()='Inactief']";
        public String deleted_radioBtn = "//label[normalize-space()='Verwijderd']";
        public String notPublished_radioBtn = "//label[normalize-space()='Niet gepubliceerd']";
        public String webShop_input = "//div[@class='ui fluid search dropdown mb-3 selection']//input[@class='search']";
        public String webShopActive_input = "//div[@class='ui fluid search dropdown mb-3 selection active visible']//input[@class='search']";
        public String search_fld = "//*[@placeholder='Zoek op Klant #, Bedrijfsnaam']";
        public String location_search_fld = "//*[@placeholder='Zoek op stad, bedrijfsnaam en url , ']";
        public String websites_search_fld = "//*[@placeholder='Zoek op Bedrijfsnaam, Webshop URL, Klant #']";
        public String bestellingen_search_fld = "//*[@placeholder='Zoek op Ordernummer, Naam van persoon']";
        public String aanvragen_search_fld = "//*[@placeholder='Zoek op Naam, Email, Land, Subcategorie, Lead ID']";
        public String lead_management_search_fld = "//*[@placeholder='Zoek op Bedrijfsnaam, Contactpersoon']";
        public String vehicle_search_fld = "//*[@placeholder='Zoek op voertuigID, merk of model']";
        public String producten_search_fld = "//*[@placeholder='Zoek op product titel, artikelnummer, EAN nummer of product ID']";
        public String adsMobileDe_search_fld = "//*[@placeholder='Zoek op Bedrijfsnaam, Kundennr']";
        public String accountsMobileDe_search_fld = "//*[@placeholder='Zoek op Bedrijfsnaam Kundennr. API code']";
        public String categories_search_fld = "//*[@placeholder='Zoek op Naam, Key']";
        public String characteristics_search_fld = "//*[@placeholder='Zoek op Naam, Key']";
        public String properties_search_fld = "//*[@placeholder='Zoek op Naam, Validatietype, Key']";
    }

    public interface AddProductPageBackEnd {
        public String add_product_btn = "//*[@class='btn btn-primary']";
        public String product_information_lbl = "//h3[contains(text(),'Productinformatie')]";
        public String verify_lbl = "//a[contains(text(),'Handmatig producttype selecteren?')]";
        public String product_type_input = "//*[@class='search' and @autocomplete='off']";
        public String suggestion_option = "//*[@class='menu transition visible']";
        public String title_lbl = "//label[contains(text(),'Titel *')]";
        public String title_input = "//*[@name='title']";
        public String desc_input = "//*[@class='fr-element fr-view' and @dir='ltr']";
        public String all_field_chkbox = "//*[@class='checkBoxValid' and @for='IsProductShowField']";
        public String brand_drpdown = "//select[@id='merk']";
        public String model_drpdown = "//select[@id='model']//following-sibling::div[@class='btn-group']//*[@class='multiselect dropdown-toggle btn btn-default']";
        public String type_drpdown = "//select[@id='type']//following-sibling::div[@class='btn-group']//*[@class='multiselect dropdown-toggle btn btn-default']";
        public String cond_drpdown = "//select[@id='593' or @id='115' or @id='595']//following-sibling::input[contains(@class,'search')]";
        public String merge_chkbox = "//label[contains(text(),'Marge')]";
        public String price_on_request_chkbox = "//label[contains(text(),'Prijs op aanvraag')]";
        public String BTW_chkbox = "//label[contains(text(),'Exclusief BTW')]";
        public String stocks_input = "//input[@placeholder='Nummer']";
        public String product_activate_chkbox = "//label[contains(text(),'Product actief laten op het moment dat er geen voo')]";
        public String allow_payment_chkbox = "//label[contains(text(),'Sta toe dat een product afgerekend wordt welke nie')]";
        public String warehouser_location__input = "//input[@id='product_150']";
        public String internal_number__input = "//input[@id='product_125']";
        public String episode_drpdown = "//select[@id='71']//following-sibling::input[contains(@class,'search')]";
        public String dimensionL_input = "//input[@name='addProductInfo.product.DimensionL']";
        public String dimensionB_input = "//input[@name='addProductInfo.product.DimensionB']";
        public String dimensionH_input = "//input[@name='addProductInfo.product.DimensionH']";
        public String specialShippingRate_input = "//div[@id='attributeValue_152']//input";
        public String weight_input = "//div[@id='attributeValue_148']//input";
        public String orderNo_input = "//input[@id='index']";
        public String articleNo_input = "//input[@id='product_158']";
        public String EAN_input = "//input[@id='product_149']";
        public String all_characteristics_chkbox = "//*[@class='checkBoxValid' and @for='checkbox13']";
        public String yes_chkbox = "//input[@id='checkbox4_34686']";
        public String damage_chkbox = "//input[@id='checkbox4_34686']";
        public String mounting_drpdown = "//select[@id='281' or @id='211' or @id='465']//following-sibling::input[@class='search']";
        public String suitable_drpdown = "//select[@id='464']//following-sibling::input[contains(@class,'search')]";
        public String inchesSize_drpdown = "//select[@id='158']//following-sibling::input[contains(@class,'search')]";
        public String rimWidth_drpdown = "//select[@id='273']//following-sibling::input[contains(@class,'search')]";
        public String pitchSize_drpdown = "//select[@id='258']//following-sibling::input[contains(@class,'search')]";
        public String hubDiameter_drpdown = "//select[@id='224']//following-sibling::input[contains(@class,'search')]";
        public String etValue_drpdown = "//select[@id='131']//following-sibling::input[contains(@class,'search')]";
        public String inchesSizeRims_drpdown = "//select[@id='153']//following-sibling::input[contains(@class,'search')]";
        public String rimsWidthBrodset_drpdown = "//select[@id='272']//following-sibling::input[contains(@class,'search')]";
        public String bandwidth_drpdown = "//select[@id='78']//following-sibling::input[contains(@class,'search')]";
        public String tireHeight_drpdown = "//select[@id='89']//following-sibling::input[contains(@class,'search')]";
        public String inchSizeBand_drpdown = "//select[@id='152']//following-sibling::input[contains(@class,'search')]";
        public String loadIndexCapacity_drpdown = "//select[@id='182']//following-sibling::input[contains(@class,'search')]";
        public String speedRating_drpdown = "//select[@id='254']//following-sibling::input[contains(@class,'search')]";
        public String treadDepthFrontLeft_drpdown = "//select[@id='234']//following-sibling::input[contains(@class,'search')]";
        public String profileDepthRightFront_drpdown = "//select[@id='237']//following-sibling::input[contains(@class,'search')]";
        public String treadDepthRearLeft_drpdown = "//select[@id='233']//following-sibling::input[contains(@class,'search')]";
        public String treadDepthRightRear_drpdown = "//select[@id='236']//following-sibling::input[contains(@class,'search')]";
        public String season_drpdown = "//select[@id='252']//following-sibling::input[contains(@class,'search')]";
        public String tireBrandFor_drpdown = "//select[@id='88' or @id='86']//following-sibling::input[contains(@class,'search')]";
        public String rearTireBrand_drpdown = "//select[@id='87']//following-sibling::input[contains(@class,'search')]";
        public String tireLabelFuelConsumption_drpdown = "//select[@id='83']//following-sibling::input[contains(@class,'search')]";
        public String tireLabelSafety_drpdown = "//select[@id='85']//following-sibling::input[contains(@class,'search')]";
        public String tireLabelNoiseProduction_drpdown = "//select[@id='84']//following-sibling::input[contains(@class,'search')]";
        public String runFlat_chkbox = "//input[@id='checkbox4_33265']";
        public String extraLoad_chkbox = "//input[@id='checkbox4_34169']";
        public String breedSet_lbl = "//label[normalize-space()='Breedset:']";
        public String breedSet_chkbox = "//input[@id='checkbox4_34402']";
        public String pitchSizeBroadset_drpdown = "//select[@id='104']//following-sibling::input[contains(@class,'search')]";
        public String hubDiameterBroadset_drpdown = "//select[@id='223']//following-sibling::input[contains(@class,'search')]";
        public String etValueBroadset_drpdown = "//select[@id='101']//following-sibling::input[contains(@class,'search')]";
        public String rimMaterial_drpdown = "//select[@id='192' or @id='193']//following-sibling::input[contains(@class,'search')]";
        public String rimBrand_drpdown = "//select[@id='203']//following-sibling::input[contains(@class,'search')]";
        public String ethnicity_drpdown = "//select[@id='70']//following-sibling::input[contains(@class,'search')]";
        public String leftFrontDamage_chkbox = "//div[@id='attributeValue_245']//input[@type='checkbox']";
        public String rightFrontDamage_chkbox = "//div[@id='attributeValue_248']//input[@type='checkbox']";
        public String leftRearDamage_chkbox = "//div[@id='attributeValue_244']//input[@type='checkbox']";
        public String rightRearDamage_chkbox = "//div[@id='attributeValue_247']//input[@type='checkbox']";
        public String fitting_costs_input = "//input[@id='product_27']";
        public String priceType_drpdown = "//select[@id='459']//following-sibling::input[@class='search']";
        public String all_characteristicsOption_chkbox = "//*[@class='checkBoxValid' and @for='IsAttributesShowField']";
        public String modelType_input = "//input[@id='product_83']";
        public String save_next_btn = "//button[contains(text(),'Opslaan en volgende')]";
        public String browse_btn = "//div[@class='btn btn-default btn-file']";
        public String publish_btn = "//button[contains(text(),'Publiceren')]";
        public String colorCode_input = "//input[@id='product_20']";
        public String assemblycosts_input = "//input[@id='product_27']";
        public String marktplaatsnl_btn = "//span[contains(text(),'Marktplaats.nl')]";
        public String uitvoeren_btn = "//button[contains(text(),'Uitvoeren')]";
        public String dehands_btn = "//span[contains(text(),'2dehands.be')]";
    }


    public interface AddVehiclePageBackEnd {
        public String vehicle_opt = "//span[contains(text(),'Voertuigen')]";
        public String add_vehicle_btn = "//*[@class='btn btn-primary']";
        public String vehicle_information_lbl = "//h3[contains(text(),'Details')]";
        public String all_data_chkbox = "//label[contains(text(),'Toon verborgen velden')]";
        public String vehicle_type_dropdown = "//*[@name='addVehicleInfo.SubCategoryId']";
        public String category_dropdown = "//*[@name='addVehicleInfo.ProductTypeId']";
        public String brand_dropdown = "//select[@name='makeId']//following-sibling::input[@class='search']";
        public String model_dropdown = "//select[@name='modelId']//following-sibling::input[@class='search']";
        public String desc_input = "(//div[@id='attributeValue_145']//input[@name='attribute.AttributeValue'])[2]";
        public String modelVariant_input = "(//label[@for='86']//following-sibling::input[@name='attribute.AttributeValue'])[1]";
        public String modelDesc_input = "(//label[@for='77']//following-sibling::input[@name='attribute.AttributeValue'])[1]";
        public String optionalPackage_input = "//input[@id='vehicle_87']";
        public String modelCode_input = "//input[@id='vehicle_90']";
        public String additionalTitleDesc_input = "(//label[@for='88']//following-sibling::input[@name='attribute.AttributeValue'])[1]";
        public String extraDesc_input = "(//label[@for='89']//following-sibling::input[@name='attribute.AttributeValue'])[1]";
        public String condition_dropdown = "//select[@id='287']//following-sibling::input[@class='search']";
        public String subcategory_dropdown = "//select[@id='286']//following-sibling::input[@class='search']";
        public String typeOfDrive_dropdown = "//select[@id='351']//following-sibling::input[@class='search']";
        public String runningHours_input = "//input[@id='OPERATING_HOURS']";
        public String mileage_input = "//input[@id='MILEAGE']";
        public String licenceWeight_input = "//input[@id='LICENSED_WEIGHT']";
        public String first_reg_date = "//input[@id='FIRST_REGISTRATION']";
        public String construction_year_input = "//input[@id='CONSTRUCTION_YEAR']";
        public String first_models_prod_date = "//input[@id='FIRST_MODELS_PRODUCTION_DATE']";
        public String construction_date = "//input[@id='CONSTRUCTION_DATE']";
        public String transmission_dropdown = "//select[@id='288']//following-sibling::input[@class='search']";
        public String CC_input = "//input[@id='CUBIC_CAPACITY']";
        public String axses_input = "//input[@id='AXLES']";
        public String loadCapacity_input = "//input[@id='LOAD_CAPACITY']";
        public String fuel_dropdown = "//select[@id='289']//following-sibling::input[@class='search']";
        public String E10_chkbox = "//label[@for='checkbox4_36195']//parent::div//input[@type='checkbox']";
        public String biodiesl_chkbox = "//label[@for='checkbox4_36200']//parent::div//input[@type='checkbox']";
        public String bioDiesl_chkbox = "//label[@for='checkbox4_36199']//parent::div//input[@type='checkbox']";
        public String height_input = "//input[@id='vehicle_129']";
        public String machineHeight_input = "//input[@id='INSTALLATION_HEIGHT']";
        public String liftingCapactiy_input = "//input[@id='LIFTING_CAPACITY']";
        public String liftHeight_input = "//input[@id='LIFTING_HEIGHT']";
        public String width_input = "//input[@id='vehicle_128']";
        public String lengthMM_input = "//input[@id='vehicle_130']";
        public String bodylength_input = "//input[@id='CONSTRUCTION_LENGTH']";
        public String length_input = "//input[@id='LOADINGSPACE_LENGTH']";
        public String power_input = "//input[@id='POWER']";
        public String loadingWidth_input = "//input[@id='LOADINGSPACE_WIDTH']";
        public String loadingHeight_input = "//input[@id='LOADINGSPACE_HEIGHT']";
        public String storageSpaces_input = "//input[@id='EUROPALLET_STORAGE_SPACES']";
        public String shippingVolume_input = "//input[@id='SHIPPING_VOLUME']";
        public String combine_power_input = "//input[@id='CONSUMPTION_POWER_COMBINED']";
        public String battery_dropdown = "//select[@id='382']//following-sibling::input[@class='search']";
        public String battery_capacity_input = "//input[@id='BATTERY_CAPACITY']";
        public String build_for_dropdown = "//select[@id='597']//following-sibling::input[@class='search']";
        public String available_dropdown = "//select[@id='603']//following-sibling::input[@class='search']";
        public String typeOfCabin_dropdown = "//select[@id='350']//following-sibling::input[@class='search']";
        public String reg_gen_input = "//input[@id='FIRST_REGISTRATION_GENERATED']";
        public String mobiledeAdId_input = "//input[@id='mobiledeAdId']";
        public String savenext_btn = "//button[@id='generalDetailsSaveButton']";
        public String license_plate_lbl = "//label[contains(text(),'Kenteken')]";
        public String license_plate_input = "//input[@id='vehicle_82']";
        public String work_status_chkbox = "//input[@id='checkbox4_44144']";
        public String internal_number_input = "//input[@id='vehicle_125']";
        public String cabin_chkbox = "//input[@id='checkbox4_36285']";
        public String door_count_input = "//input[@id='DOOR_COUNT']";
        public String sliding_door_dropdown = "//select[@id='379']//following-sibling::input[@class='search']";
        public String charis_input = "//input[@id='SEAT_COUNT']";
        public String color_dropdown = "//select[@id='306']//following-sibling::input[@class='search']";
        public String metalic_chkbox = "//label[@for='checkbox4_36242']//parent::div//input[@type='checkbox']";
        public String metalicColor_chkbox = "//label[@for='checkbox4_36258']//parent::div//input[@type='checkbox']";
        public String man_color_name_input = "//input[@id='vehicle_48']";
        public String damage_dropdown = "//select[@id='315']//following-sibling::input[@class='search']";
        public String damage_history_dropdown = "//select[@id='316' or @id='315']//following-sibling::input[@class='search']";
        public String roadworthy_dropdown = "//select[@id='317']//following-sibling::input[@class='search']";
        public String previousOwner_input = "//input[@id='NUMBER_OF_PREVIOUS_OWNERS']";
        public String warranty_chkbox = "//label[@for='checkbox4_36454']//parent::div//input[@type='checkbox']";
        public String nonsmokingVehicle_chkbox = "//label[@for='checkbox4_36259']//parent::div//input[@type='checkbox']";
        public String fullServiceHistory_chkbox = "//label[@for='checkbox4_36258']//parent::div//input[@type='checkbox']";
        public String fuelCity_input = "//input[@id='CONSUMPTION_INNER']";
        public String fuelOutSideCity_input = "//input[@id='CONSUMPTION_OUTER']";
        public String combineFuel_input = "//input[@id='CONSUMPTION_COMBINED']";
        public String enegry_dropdown = "//select[@id='596']//following-sibling::input[@class='search']";
        public String emission_dropdown = "//select[@id='305']//following-sibling::input[@class='search']";
        public String environmental_dropdown = "//select[@id='304']//following-sibling::input[@class='search']";
        public String diesel_filter_chkbox = "//label[@for='checkbox4_36198']//parent::div//input[@type='checkbox']";
        public String MOT_date = "//input[@id='APK_VALID_UNTIL']";
        public String newMOT_chkbox = "//input[@id='checkbox4_36257']";
        public String municipalGovernmentVehicle_chkbox = "//input[@id='checkbox4_36340']";
        public String roadLicence_chkbox = "//input[@id='checkbox4_36372']";
        public String co2_input = "//input[@id='CO2']";
        public String chassisNummer_input = "//input[@id='vehicle_40']";
        public String taxi_chkbox = "//input[@id='checkbox4_36268']";
        public String taxiOption_chkbox = "//input[@id='checkbox4_36340']";
        public String save_next_btn = "//button[contains(text(),'Opslaan en volgende')]";
        public String airConditioning_label = "//label[contains(text(),'Airconditioning')]";
        public String electircStart_label = "//label[normalize-space()='Elektrische start']";
        public String electircStart_chkbox = "//input[@id='checkbox4_36321']";
        public String catalyst_chkbox = "//input[@id='checkbox4_36197']";
        public String kickstarter_chkbox = "//input[@id='checkbox4_36335']";
        public String ac_dropdown = "//select[@id='338']//following-sibling::input[@class='search']";
        public String androidAuto_chkbox = "//label[@for='checkbox4_36423']//parent::div//input[@type='checkbox']";
        public String appleCarPlay_chkbox = "//label[@for='checkbox4_36422']//parent::div//input[@type='checkbox']";
        public String cargoNet_chkbox = "//label[@for='checkbox4_36430']//parent::div//input[@type='checkbox']";
        public String upholstery_dropdown = "//select[@id='310']//following-sibling::input[@class='search']";
        public String colorInterior_dropdown = "//select[@id='309']//following-sibling::input[@class='search']";
        public String passengerSeatFullyFoldable_chkbox = "//label[@for='checkbox4_36428']//parent::div//input[@type='checkbox']";
        public String bluetooth_chkbox = "//label[@for='checkbox4_36281']//parent::div//input[@type='checkbox']";
        public String boardComputer_chkbox = "//label[@for='checkbox4_36342']//parent::div//input[@type='checkbox']";
        public String wirelessChargingSmartphone_chkbox = "//label[@for='checkbox4_36426']//parent::div//input[@type='checkbox']";
        public String powerSteering_chkbox = "//label[@for='checkbox4_36367']//parent::div//input[@type='checkbox']";
        public String cdPlayer_chkbox = "//label[@for='checkbox4_36287']//parent::div//input[@type='checkbox']";
        public String cdChanger_chkbox = "//label[@for='checkbox4_36286']//parent::div//input[@type='checkbox']";
        public String centralDoorLocking_chkbox = "//label[@for='checkbox4_36288']//parent::div//input[@type='checkbox']";
        public String digitalCockpit_chkbox = "//label[@for='checkbox4_36424']//parent::div//input[@type='checkbox']";
        public String dimmingInteriorMirror_chkbox = "//label[@for='checkbox4_36429']//parent::div//input[@type='checkbox']";
        public String navigation_chkbox = "//label[@for='checkbox4_36341']//parent::div//input[@type='checkbox']";
        public String electricallyAdjustableSeats_chkbox = "//label[@for='checkbox4_36318']//parent::div//input[@type='checkbox']";
        public String electricallyAdjustableSeats2_chkbox = "//input[@id='checkbox4_36318']";
        public String electricallyAdjustableRearSeats_chkbox = "//label[@for='checkbox4_36419']//parent::div//input[@type='checkbox']";
        public String ElectricSeatHeating_chkbox = "//label[@for='checkbox4_36320']//parent::div//input[@type='checkbox']";
        public String ElectricRearSeatHeating_chkbox = "//label[@for='checkbox4_36406']//parent::div//input[@type='checkbox']";
        public String soundSystem_chkbox = "//label[@for='checkbox4_36407']//parent::div//input[@type='checkbox']";
        public String handsFreeCarKit_chkbox = "//label[@for='checkbox4_36327']//parent::div//input[@type='checkbox']";
        public String headUpDisplay_chkbox = "//label[@for='checkbox4_36328']//parent::div//input[@type='checkbox']";
        public String leatherSteeringWheel_chkbox = "//label[@for='checkbox4_36398']//parent::div//input[@type='checkbox']";
        public String lumbarSupport_chkbox = "//label[@for='checkbox4_36399']//parent::div//input[@type='checkbox']";
        public String massageChair_chkbox = "//label[@for='checkbox4_36400']//parent::div//input[@type='checkbox']";
        public String centerArmrest_chkbox = "//label[@for='checkbox4_36393']//parent::div//input[@type='checkbox']";
        public String multifunctionalWheel_chkbox = "//label[@for='checkbox4_36339']//parent::div//input[@type='checkbox']";
        public String musicStreamingIntegration_chkbox = "//label[@for='checkbox4_36427']//parent::div//input[@type='checkbox']";
        public String radio_dropdown = "//span[contains(text(),'None selected')]";
        public String DABRadio_select = "//*[@title='DAB-radio']";
        public String tunerRadio_select = "//*[@title='Radio / Tuner']";
        public String rainSensor_chkbox = "//label[@for='checkbox4_36449']//parent::div//input[@type='checkbox']";
        public String smokersPackage_chkbox = "//label[@for='checkbox4_36418']//parent::div//input[@type='checkbox']";
        public String ambientLighting_chkbox = "//label[@for='checkbox4_36420']//parent::div//input[@type='checkbox']";
        public String skiBag_chkbox = "//label[@for='checkbox4_36378']//parent::div//input[@type='checkbox']";
        public String sportsPackage_chkbox = "//label[@for='checkbox4_36382']//parent::div//input[@type='checkbox']";
        public String sportsSeats_chkbox = "//label[@for='checkbox4_36383']//parent::div//input[@type='checkbox']";
        public String seatVentilation_chkbox = "//label[@for='checkbox4_36435']//parent::div//input[@type='checkbox']";
        public String touchScreen_chkbox = "//label[@for='checkbox4_36408']//parent::div//input[@type='checkbox']";
        public String television_chkbox = "//label[@for='checkbox4_36388']//parent::div//input[@type='checkbox']";
        public String cabinAC_chkbox = "//input[@id='checkbox4_36375']";
        public String toilet_chkbox = "//input[@id='checkbox4_36390']";
        public String USB_chkbox = "//label[@for='checkbox4_36409']//parent::div//input[@type='checkbox']";
        public String shiftLevers_chkbox = "//label[@for='checkbox4_36405']//parent::div//input[@type='checkbox']";
        public String electricWindowControl_chkbox = "//label[@for='checkbox4_36322']//parent::div//input[@type='checkbox']";
        public String steeringWheelHeating_chkbox = "//input[@id='checkbox4_36395']";
        public String parkingHeater_chkbox = "//label[@for='checkbox4_36276']//parent::div//input[@type='checkbox']";
        public String parkingHeater2_chkbox = "//input[@id='checkbox4_36276']";
        public String kitchen_chkbox = "//input[@id='checkbox4_36336']";
        public String refrigerator_chkbox = "//input[@id='checkbox4_36297']";
        public String sleepingCabin_chkbox = "//input[@id='checkbox4_36308']";
        public String sleepingCharis_chkbox = "//input[@id='checkbox4_36380']";
        public String partition_chkbox = "//input[@id='checkbox4_36309']";
        public String windscreenHeating_chkbox = "//label[@for='checkbox4_36394']//parent::div//input[@type='checkbox']";
        public String wifiHotspot_chkbox = "//label[@for='checkbox4_36421']//parent::div//input[@type='checkbox']";
        public String image_btn = "//span[contains(text(),'Selecteer')]";
        public String save_btn = "//button[@id='interiorSaveButton']";
        public String tire_lbl = "//label[contains(text(),'All Season banden')]";
        public String crane_lbl = "//label[contains(text(),'Kraan')]";
        public String towar_lbl = "//label[contains(text(),'Trekhaak')]";
        public String frontHydraulics_lbl = "//label[normalize-space()='Fronthydrauliek']";
        public String adaptedForDisabled_lbl = "//label[normalize-space()='Aangepast voor mindervaliden']";
        public String adaptedForDisabled_chkbox = "//input[@id='checkbox4_36306']";
        public String storageCases_chkbox = "//input[@id='checkbox4_36282']";
        public String crashbar_chkbox = "//input[@id='checkbox4_36373']";
        public String windshield_chkbox = "//input[@id='checkbox4_36391']";
        public String frontHydraulics_chkbox = "//input[@id='checkbox4_36325']";
        public String frontLift_chkbox = "//input[@id='checkbox4_40794']";
        public String powerSteering_lbl = "//label[normalize-space()='Stuurbekrachtiging']";
        public String tire_chkbox = "//input[@id='checkbox4_36413']";
        public String crane_chkbox = "//input[@id='checkbox4_36299']";
        public String tailgate_chkbox = "//input[@id='checkbox4_36386']";
        public String corneringLighting_dropdown = "//select[@id='327']//following-sibling::input[@class='search']";
        public String daytimeRunningLights_dropdown = "//select[@id='344']//following-sibling::input[@class='search']";
        public String roofRails_chkbox = "//label[@for='checkbox4_36374']//parent::div//input[@type='checkbox']";
        public String electricallyAdjustableExteriorMirrors_chkbox = "//label[@for='checkbox4_36319']//parent::div//input[@type='checkbox']";
        public String electricTailgate_chkbox = "//label[@for='checkbox4_36397']//parent::div//input[@type='checkbox']";
        public String headLamp_dropdown = "//select[@id='380']//following-sibling::input[@class='search']";
        public String headlampWashers_chkbox = "//label[@for='checkbox4_36416']//parent::div//input[@type='checkbox']";
        public String alloyWheels_chkbox = "//label[@for='checkbox4_36275']//parent::div//input[@type='checkbox']";
        public String airSuspension_chkbox = "//label[@for='checkbox4_36274']//parent::div//input[@type='checkbox']";
        public String frontFogLights_chkbox = "//label[@for='checkbox4_36324']//parent::div//input[@type='checkbox']";
        public String panoramaRoof_chkbox = "//label[@for='checkbox4_36343']//parent::div//input[@type='checkbox']";
        public String steelRims_chkbox = "//label[@for='checkbox4_36414']//parent::div//input[@type='checkbox']";
        public String heatedExteriorMirrors_chkbox = "//input[@id='checkbox4_39826']";
        public String towbar_dropdown = "//select[@id='383']//following-sibling::input[@class='search']";
        public String winterTires_chkbox = "//label[@for='checkbox4_36412']//parent::div//input[@type='checkbox']";
        public String sunroof_chkbox = "//label[@for='checkbox4_36384']//parent::div//input[@type='checkbox']";
        public String summerTires_chkbox = "//label[@for='checkbox4_36453']//parent::div//input[@type='checkbox']";
        public String ABS_lbl = "//label[contains(text(),'ABS')]";
        public String securityRoof_lbl = "//label[normalize-space()='Veiligheidsdak']";
        public String securityRoof_chkbox = "//input[@id='checkbox4_36368']";
        public String ABS_chkbox = "//label[@for='checkbox4_36269']//parent::div//input[@type='checkbox']";
        public String abs_chkbox = "//input[@id='checkbox4_36269']";
        public String distanceAlert_chkbox = "//label[@for='checkbox4_36450']//parent::div//input[@type='checkbox']";
        public String airbags_dropdown = "//select[@id='320']//following-sibling::input[@class='search']";
        public String alarm_chkbox = "//label[@for='checkbox4_36392']//parent::div//input[@type='checkbox']";
        public String tirePressureSensor_chkbox = "//label[@for='checkbox4_36404']//parent::div//input[@type='checkbox']";
        public String cruiseControl_dropdown = "//select[@id='342']//following-sibling::input[@class='search']";
        public String deadAngleDetection_chkbox = "//label[@for='checkbox4_36437']//parent::div//input[@type='checkbox']";
        public String ESPElectronicStabilityControl_chkbox = "//label[@for='checkbox4_36323']//parent::div//input[@type='checkbox']";
        public String retarderIntarder_chkbox = "//input[@id='checkbox4_36371']";
        public String highBeamAssist_chkbox = "//label[@for='checkbox4_36411']//parent::div//input[@type='checkbox']";
        public String glareFreeHighBeam_chkbox = "//label[@for='checkbox4_36415']//parent::div//input[@type='checkbox']";
        public String tractionControl_chkbox = "//label[@for='checkbox4_36387']//parent::div//input[@type='checkbox']";
        public String hillStartAssist_chkbox = "//label[@for='checkbox4_36396']//parent::div//input[@type='checkbox']";
        public String isofix_chkbox = "//label[@for='checkbox4_36334']//parent::div//input[@type='checkbox']";
        public String isofixPassengerSeat_chkbox = "//label[@for='checkbox4_36425']//parent::div//input[@type='checkbox']";
        public String keylessEntry_chkbox = "//label[@for='checkbox4_36434']//parent::div//input[@type='checkbox']";
        public String laneChangeAssist_chkbox = "//label[@for='checkbox4_36436']//parent::div//input[@type='checkbox']";
        public String lightSensor_chkbox = "//label[@for='checkbox4_36337']//parent::div//input[@type='checkbox']";
        public String nightVision_chkbox = "//label[@for='checkbox4_36402']//parent::div//input[@type='checkbox']";
        public String emergencyCallSystem_chkbox = "//label[@for='checkbox4_36403']//parent::div//input[@type='checkbox']";
        public String emergencyBrakeAssistant_chkbox = "//label[@for='checkbox4_36433']//parent::div//input[@type='checkbox']";
        public String parkingSensors_dropdown = "//span[contains(text(),'None selected')]";
        public String flatTireBreakdown_dropdown = "//select[@id='381']//following-sibling::input[@class='search']";
        public String plugInHybrid_chkbox = "//label[@for='checkbox4_36196']//parent::div//input[@type='checkbox']";
        public String suitableForWheelchairs_chkbox = "//label[@for='checkbox4_36305']//parent::div//input[@type='checkbox']";
        public String rangeExtender_chkbox = "//label[@for='checkbox4_36432']//parent::div//input[@type='checkbox']";
        public String fatigueDetection_chkbox = "//label[@for='checkbox4_36401']//parent::div//input[@type='checkbox']";
        public String speedLimiter_chkbox = "//label[@for='checkbox4_36431']//parent::div//input[@type='checkbox']";
        public String sportsSuspension_chkbox = "//label[@for='checkbox4_36203']//parent::div//input[@type='checkbox']";
        public String startStopSystem_chkbox = "//label[@for='checkbox4_36204']//parent::div//input[@type='checkbox']";
        public String immobilizer_chkbox = "//label[@for='checkbox4_36333']//parent::div//input[@type='checkbox']";
        public String voiceControl_chkbox = "//label[@for='checkbox4_36455']//parent::div//input[@type='checkbox']";
        public String trafficSignRecognition_chkbox = "//label[@for='checkbox4_36410']//parent::div//input[@type='checkbox']";
        public String fourWheelDrive_chkbox = "//label[@for='checkbox4_36186']//parent::div//input[@type='checkbox']";
        public String winterPackage_chkbox = "//label[@for='checkbox4_36417']//parent::div//input[@type='checkbox']";
        public String vehicleSpecificComments_lbl = "(//label[contains(text(),'Voertuig specifieke opmerkingen')])[1]";
        public String vehicleSpecificComments_input = "(//div[@class='fr-element fr-view'])[1]";
        public String standardVehicleComments_input = "(//div[@class='fr-element fr-view'])[3]";
        public String warrantyDescription_input = "(//div[@class='fr-element fr-view'])[5]";
        public String providerStandardComments_input = "(//div[@class='fr-element fr-view'])[7]";
        public String standardCommentsPortals_input = "(//div[@class='fr-element fr-view'])[9]";
        public String otherProperties_input = "(//div[@class='fr-element fr-view'])[11]";
        public String otherOptions_input = "(//div[@class='fr-element fr-view'])[13]";
        public String otherOptionsTranslated_lbl = "(//label[contains(text(),'Overige opties | Vertaald')])[1]";
        public String highlights1_input = "//input[@id='vehicle_131']";
        public String highlights2_input = "//input[@id='vehicle_132']";
        public String highlights3_input = "//input[@id='vehicle_133']";
        public String forTradeExImport_chkbox = "//input[@id='checkbox4_36452']";
        public String priceOnRequest_chkbox = "//input[@id='checkbox4_40631']";
        public String salesPriceNL_input = "//div[@id='attributeValue_102']//input";
        public String exportPrice_input = "//div[@id='attributeValue_104']//input";
        public String pricePortalNL_input = "//div[@id='attributeValue_106']//input";
        public String pricePortalExport_input = "//div[@id='attributeValue_108']//input";
        public String priceNLB2BTradingPrice_input = "//div[@id='attributeValue_103']//input";
        public String priceExportB2B_input = "//div[@id='attributeValue_105']//input";
        public String pricePortalNLB2B_input = "//div[@id='attributeValue_107']//input";
        public String pricePortalExportB2B_input = "//div[@id='attributeValue_109']//input";
        public String VATReclaimable_dropdown = "//select[@id='537']//following-sibling::input[@class='search']";
        public String SalesPriceNLExVAT_dropdown = "//select[@id='552']//following-sibling::input[@class='search']";
        public String salesPriceNLExBPM_dropdown = "//select[@id='553']//following-sibling::input[contains(@class,'search')]";
        public String exportPriceExVAT_dropdown = "//select[@id='549']//following-sibling::input[contains(@class,'search')]";
        public String exportPriceExBPM_dropdown = "//select[@id='548']//following-sibling::input[contains(@class,'search')]";
        public String exVATPortalNL_dropdown = "//select[@id='545']//following-sibling::input[contains(@class,'search')]";
        public String exBPMPortalNL_dropdown = "//select[@id='544']//following-sibling::input[contains(@class,'search')]";
        public String exVATPortalExport_dropdown = "//select[@id='541']//following-sibling::input[contains(@class,'search')]";
        public String exBPMPortalExport_dropdown = "//select[@id='540']//following-sibling::input[contains(@class,'search')]";
        public String exVATNLB2B_dropdown = "//select[@id='551']//following-sibling::input[contains(@class,'search')]";
        public String exBPMNLB2B_dropdown = "//select[@id='550']//following-sibling::input[contains(@class,'search')]";
        public String exVATExportB2B_dropdown = "//select[@id='547']//following-sibling::input[contains(@class,'search')]";
        public String exBPMExportB2B_dropdown = "//select[@id='546']//following-sibling::input[contains(@class,'search')]";
        public String exVATPortalNLB2B_dropdown = "//select[@id='543']//following-sibling::input[contains(@class,'search')]";
        public String exBPMPortalNLB2B_dropdown = "//select[@id='542']//following-sibling::input[contains(@class,'search')]";
        public String exVATPortalExportB2B_dropdown = "//select[@id='539']//following-sibling::input[contains(@class,'search')]";
        public String exBPMPortalExportB2B_dropdown = "//select[@id='538']//following-sibling::input[contains(@class,'search')]";
        public String centralLubricationUnit_lbl = "//label[contains(text(),'Centrale smeereenheid')]";
        public String centralLubricationUnit_chkbox = "//input[@id='checkbox4_36289']";
        public String BSS_lbl = "//label[contains(text(),'BSS')]";
        public String BSS_chkbox = "//input[@id='checkbox4_36283']";
        public String mechanicalQuickCoupling_chkbox = "//input[@id='checkbox4_36369']";
        public String marktplaatsnl_btn = "//span[contains(text(),'Marktplaats.nl')]";
        public String uitvoeren_btn = "//button[contains(text(),'Uitvoeren')]";
        public String dehands_btn = "//span[contains(text(),'2dehands.be')]";
        public String mobilede_btn = "(//span[contains(text(),' mobile.de')])[3]";
    }
}