cmd /c "directAutosRegister_1743.bat"
cmd /c "directAutosLogin_1748.bat"
cmd /c "directAutosAllContactFunctionality_1750.bat"
cmd /c "directAutosPagingSortingFunctionality_1753.bat"
cmd /c "directAutosProductDetailsPage_1754.bat"
cmd /c "directAutosSearchFunctionality_1752.bat"
cmd /c "directAutosAddProductGuestUser_1751.bat"
cmd /c "directAutosAddProductLoginUser_1751.bat"